const LIST_STUDENT = "LIST_STUDENT";
const SET_PROPERTY_STUDENT = "SET_PROPERTY_STUDENT";
const SET_STUDENT = "SET_STUDENT";
const OPEN_FORM_STUDENT = "OPEN_FORM_STUDENT";
const CLOSE_FORM_STUDENT = "CLOSE_FORM_STUDENT";

export { LIST_STUDENT, SET_PROPERTY_STUDENT, SET_STUDENT, OPEN_FORM_STUDENT, CLOSE_FORM_STUDENT }